# Generated by Django 5.2.8 on 2025-12-02 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0005_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="show_name",
            field=models.BooleanField(default=True),
        ),
    ]
